controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["front_left_wheel_joint", "rear_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint", "rear_right_wheel_joint"]
    
    wheel_separation: 1.0
    wheel_separation_multiplier: 1.0
    wheel_radius: 0.2
    wheels_per_side: 2

    cmd_vel_timeout: 0.5
    pose_reference_frame: "odom"
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    enable_odom_tf: true

    use_stamped_vel: false # Change when using nodes to publish messages
    open_loop: true

    pose_covariance_diagona: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]