# Right camera of Realsense D435

image_width: 1280
image_height: 720

camera_name: realsense_d435_right

camera_matrix:
  rows: 3
  cols: 3
  data: [920.0, 0.0, 640.0,
         0.0, 920.0, 360.0,
         0.0, 0.0, 1.0]

distortion_model: plumb_bob

distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.0, 0.0, 0.0, 0.0, 0.0]

rectification_matrix:
  rows: 3
  cols: 3
  data: [1.0, 0.0, 0.0,
         0.0, 1.0, 0.0,
         0.0, 0.0, 1.0]

projection_matrix:
  rows: 3
  cols: 4
  data: [920.0, 0.0, 640.0, -46.0, # -46.0 = -fx * baseline = -920 * 0.05m
         0.0, 920.0, 360.0, 0.0,
         0.0, 0.0, 1.0, 0.0]
